variables:
  NPM_TOKEN: "test"


stages:
  - build
  - test

before_script:
  - apt-get update
  - apt-get install -y sudo
job_build:
  stage: build
  script:
    - echo "Building the project"

job_test:
  image: mcr.microsoft.com/playwright:v1.42.1-jammy
  stage: test
  script:
    - echo "Running tests"
    - npm i
    - npx playwright install && npx playwright install --with-deps
    - npm run e2e
