variables:
  NPM_TOKEN: "test"


stages:
  - test

test:
  stage: test
  image: node:latest
  before_script:
    - npm install playwright
    # Install any other dependencies your tests require
  script:
    - npx playwright install
    - playwright test
