variables:
  NPM_TOKEN: "test"

image: mcr.microsoft.com/playwright:v1.44.0-jammy

stages:
  - build
  - test
  - tgMessageIffail

job_build:
  stage: build
  script:
    - echo "Building the project"

job_test:
  # image: node:latest
  stage: test
  parallel: 2
  script:
    - echo "Running tests"
    - echo $CI_NODE_INDEX
    - echo $CI_NODE_TOTAL
    - npm ci
    - npx playwright install
    - npx playwright install-deps
    - npm run e2e -- --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL

job_onFail:
  stage: tgMessageIffail
  when: on_failure
  script: 
    - npm install
    - node source/utils/cibot.ts
