stages:
  - test

test:
  stage: test
  image: node:latest
  before_script:
    - sudo npm install -g playwright
    # Install any other dependencies your tests require
  script:
    - playwright install
    - playwright test
