variables:
  NPM_TOKEN: "test"


stages:
  - build
  - test

job_build:
  stage: build
  script:
    - echo "Building the project"

job_test:
  image: mcr.microsoft.com/playwright:v1.42.1-jammy
  stage: test
  script:
    - echo "Running tests"
    - npm i
    - sudo npx playwright install
    - npm run e2e
