variables:
  NPM_TOKEN: "test"

image: mcr.microsoft.com/playwright:bionic

stages:
  - build
  - test

job_build:
  stage: build
  script:
    - echo "Building the project"

job_test:
  stage: test
  script:
    - echo "Running tests"
    - npm i
    - npx playwright install && npx playwright install --with-deps
    - npm run e2e
