variables:
  NPM_TOKEN: "test"

image: mcr.microsoft.com/playwright:v1.20.0-focal

stages:
  - setup
  - build
  - test

setup:
  stage: setup
  script:
    # Установка nvm
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - source "$NVM_DIR/nvm.sh"
    # Установка последней версии Node.js
    - nvm install node
    - node --version
    - npm --version

job_build:
  stage: build
  script:
    - echo "Building the project"

job_test:
  # image: node:latest
  stage: test
  parallel: 2
  script:
    - echo "Running tests"
    - echo $CI_NODE_INDEX
    - echo $CI_NODE_TOTAL
    - npm i
    - npm install -g typescript
    - npx playwright install-deps 
    - npx playwright install
    - npm run e2e -- --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL

